org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true

mod_id=wayfinder
mod_name=Wayfinder
mod_license=All Rights Reserved
mod_version=0.1.0-dev
mod_group_id=com.wayfinder
mod_authors=Rhian Nicholson
mod_description=An environmental archaeology and navigation mod where structures, landscape, and history form a discoverable Wayfinder network.

minecraft_version=26.2
neo_version=26.2.0.62
